name: essensbestellung-test

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    env_file:
      - ../.env.dev
    environment:
      - REFLEX_MODE=test
    volumes:
      - ..:/src
      - node_modules:/src/node_modules
      - bun_install:/root/.bun
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    env_file:
      - ../.env.dev

volumes:
  node_modules:
  bun_install: