name: essensbestellung-dev

services:
  reflex:
    build:
      # The files for the reflex container lie in the project root
      # Which means we have to navigate to the parent directory using ..
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../.env.dev
    volumes:
      - ..:/src
      - ../logs:/src/logs
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:17
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../.env.dev

volumes:
 postgres_data_dev: