FROM python:3.12

WORKDIR /src

RUN pip install playwright

RUN playwright install

RUN playwright install-deps

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["tail", "-f", "/dev/null"]